"""Init

Revision ID: b2758084d1a8
Revises: 233aa49bc990
Create Date: 2023-02-22 11:07:36.613157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2758084d1a8'
down_revision = '233aa49bc990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
